### ISSUE TITLE
Certificate error from urllib

### ISSUE THREAD

**Issue by micromouseonline** [Bulebots/mmsim#22]
When I do the install as directed and then run mmsim, I get an error. Specifically, this error:

      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

The reason is that the Python installer on MacOs may not have run the certificate commands. 

This question on StackExchange has the answer:

https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate/44649450#44649450

**Comment by micromouseonline** [comment]
Just to be clear, this is not an issue with the mmsim code. The problem is with the way that Python may be installed under MacOS. I used the pkg installation from python.org.

The issue can be demonstrated from the Python shell:

      Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
      [Clang 6.0 (clang-600.0.57)] on darwin
      Type "help", "copyright", "credits" or "license" for more information.
      >>> from urllib.request import urlretrieve
      >>> url = 'https://github.com/micromouseonline/mazefiles/'\
      ...         'archive/master.tar.gz'
      >>> url
      'https://github.com/micromouseonline/mazefiles/archive/master.tar.gz'
      >>> reveal_tar, headers = urlretrieve(url)
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
        self.send(msg)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
        self.connect()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
        server_hostname=server_hostname)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
        session=session
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
        self.do_handshake()
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
        self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 247, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
        response = self._open(req, data)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
        '_open', req)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
        context=self._context, check_hostname=self._check_hostname)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
        raise URLError(err)
      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
      >>> exit()

**Comment by Peque** [comment]
Oh, I understand. I cannot fix that. :sweat_smile: 

However, if you confirm that you could use [`requests`](http://docs.python-requests.org/) to get content from an HTTPS source (i.e.: a GitHub page) without having those issues, I would not mind adding that extra dependency. Apparently [they use `certifi` package](http://docs.python-requests.org/en/latest/user/advanced/#ca-certificates), which may not require you to have any special system-wide configuration.

**Comment by micromouseonline** [comment]
I have already made the fix now. so it is not clear that any success I might have would not be due to the fix rather than the change. It is purely a local configuration matter. I put it up as an issue so that others might find a solution if they run into a similar problem.

Perhaps a note in the README might be appropriate?

—
Peter Harrison
peter.harrison@helicron.net

**Comment by Peque** [comment]
@micromouseonline I will leave this open, as I think a note in the README file could be appropriate, as you suggested.

Do not know whether I will add it soon or not, but definitely some day! :smile:

Pull requests accepted too. :stuck_out_tongue_winking_eye:

**Comment by micromouseonline** [comment]
Ok. It was not my issue to close really. I was just rushing through some tidying up on Github :)
—
Peter Harrison
peter.harrison@helicron.net
